### ISSUE TITLE
试用请求

### ISSUE THREAD

**Issue by sunzj1989** [wuchangyu/excel-view#1]
你好，请问你的工程能够使用么，IO那部分代码能够开放出来么

**Comment by yuyingz** [comment]
同问，有没完整功能的在线工程，在线试用一下

**Comment by wangcongxing** [comment]
同问

**Comment by kaiyuanZheng** [comment]
大佬，这个没有写license，可以开放商用吗？

**Comment by wangcongxing** [comment]
我们还在开发的，付费可以提供技术支持^_^



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kaiyuanZheng <notifications@github.com&gt;
发送时间: 2020年11月21日 16:25
收件人: wuchangyu/excel-view <excel-view@noreply.github.com&gt;
抄送: wangcongxing <2256807897@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[wuchangyu/excel-view] 试用请求 (#1)





 
大佬，这个没有写license，可以开放商用吗？

**Comment by wangcongxing** [comment]
回复错了请忽略



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kaiyuanZheng <notifications@github.com&gt;
发送时间: 2020年11月21日 16:25
收件人: wuchangyu/excel-view <excel-view@noreply.github.com&gt;
抄送: wangcongxing <2256807897@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[wuchangyu/excel-view] 试用请求 (#1)





 
大佬，这个没有写license，可以开放商用吗？
